#!/bin/bash

set -euxo pipefail

CLEAN_BUILD=1

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

[ "$CLEAN_BUILD" == 1 ] && rm -rf vel_build Velocity/build/ XboxInternals/build/
mkdir -p vel_build ; cd vel_build

mkdir -p internals ; cd internals
qmake6 -config release ../../XboxInternals/XboxInternals.pro
make -j10
cd ..

mkdir -p vel || true ; cd vel
qmake6 -config release ../../Velocity/Velocity.pro
make -j10
cd ..

cd "$SCRIPT_DIR"
find ./Velocity/build

$QT_BIN_PATH/macdeployqt6 ./Velocity/build/Velocity-OSX/release/Velocity.app
codesign --entitlements app.entitlements --deep --force --options runtime --sign "DEVELOPER_ID_HERE" ./Velocity/build/Velocity-OSX/release/Velocity.app

[ "$CLEAN_BUILD" == 1 ] && open ./Velocity/build/Velocity-OSX/release/Velocity.app/
[ "$CLEAN_BUILD" == 0 ] && ./Velocity/build/Velocity-OSX/release/Velocity.app/Contents/MacOS/Velocity
