#ifndef XBOXINTERNALS_GLOBAL_H
#define XBOXINTERNALS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XBOXINTERNALS_LIBRARY)
#  define XBOXINTERNALSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XBOXINTERNALSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XBOXINTERNALS_GLOBAL_H
